# Generated by Django 4.2.7 on 2023-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_jobpost_created_by_companydetails_jobpost_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
