# Generated by Django 4.2.7 on 2023-11-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_jobpost_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts_company_details', to='recruiter.companydetails'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts_company_name', to='recruiter.companydetails'),
        ),
    ]
