# Generated by Django 4.2.7 on 2023-11-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_jobpost_company_details_alter_jobpost_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='company_details',
            new_name='company_name_and_details',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
    ]
