# Generated by Django 4.2.7 on 2023-11-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_rename_company_details_jobpost_company_name_and_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_name_and_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.companydetails'),
        ),
    ]
