# Generated by Django 4.2.7 on 2023-11-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_alter_jobpost_company_name_and_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='company_name_and_details',
            new_name='company',
        ),
    ]
