# Generated by Django 4.2.7 on 2023-11-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_rename_company_name_and_details_jobpost_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='company_logo'),
        ),
    ]
