# Generated by Django 4.2.7 on 2023-11-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_jobpost_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_logo',
        ),
    ]
