# Generated by Django 4.2.7 on 2023-11-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_report_delete_joblistingreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
